version: '3.8'

services:

  mongodb:
    image: mongo:7
    container_name: napp-mongodb
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:${MONGO_PORT:-27017}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: napp-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/
      ME_CONFIG_BASICAUTH_ENABLED: "false"
    depends_on:
      - mongodb

  backend:
    build: ./backend
    container_name: napp-backend
    ports:
      - "${PORT:-5000}:5000"
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: always

  frontend:
    build: ./frontend
    container_name: napp-frontend
    ports:
      - "8000:80"
    depends_on:
      - backend
    restart: always

volumes:
  mongodb_data:


