sonar.projectKey=notes-app
sonar.sources=frontend/src,backend
sonar.sourceEncoding=UTF-8
# SonarQube ko report ka sahi rasta batana
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
