apiVersion: v1
kind: Secret
metadata:
  name: notes-app-secret
  namespace: noteapp
type: Opaque
stringData:
  MONGODB_URI: "mongodb://admin:NasirSecretPass12345@mongodb:27017/notes-app?authSource=admin"
  MONGO_USER: "admin"
  MONGO_PASS: "NasirSecretPass12345"