apiVersion: v1
kind: Secret

metadata:
  name: notes-app-secret
  namespace: noteapp

type: Opaque

stringData:
  MONGODB_URI: "mongodb://$(MONGO_USER):$(MONGO_PASS)@mongodb:27017/notes-app?authSource=admin"
  MONGO_USER: nasirhayat028
  MONGO_PASS: NasirHayat028
