name: Notes App CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show project structure
        run: |
          echo "CI is running!"
          echo "Repository contents:"
          ls -la

          echo "Commit: $GITHUB_SHA"
          echo "Branch: $GITHUB_REF_NAME"
