name: Test My Self Hosted Runner

on:
  push:
    branches: [ "main" ]  # Jab bhi aap main branch par code commit karenge, ye chalega

jobs:
  test-job:
    runs-on: self-hosted  # Yeh line aapke laptop wale runner ko target karegi

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run a Test Command
      run: |
        echo "Hello Nasir! Your runner is working perfectly."
        echo "Current directory is:"
        pwd
      # tracking
